[workspace]
resolver = "3"
members = [
    "core/freedom-async",
    "core/freedom-fs",
    "core/freedom-log",
    "core/freedom-plugins",
    "core/freedom-scheme",
    "core/freedom-scripts",

    "plugin/freedom-winit",
    "plugin/library",

    "freedome",
]

[workspace.dependencies]
freedom-async = { path = "core/freedom-async" }
freedom-fs = { path = "core/freedom-fs" }
freedom-log = { path = "core/freedom-log" }
freedom-plugins = { path = "core/freedom-plugins" }
freedom-scheme = { path = "core/freedom-scheme" }
freedom-scripts = { path = "core/freedom-scripts" }

log = "0.4.28"

steel-core = { git = "https://github.com/mattwparas/steel", rev = "6bb6f17be7cb0ce932816a697cfafc669490d489", features = [
    "markdown",        # Augment help functionality with markdown rendering
    "stacker",         # Grow the stack dynamically during transduction
    "triomphe",        # Use triophe library instead of std Arc
    "imbl",            # Use im library for immutable data structures
    "inline-captures", # Use smallvec instead of vec for closure captures
] }

# Optimize dependencies in dev builds
[profile.dev.package."*"]
opt-level = 3
