[package]
name = "freedom-async"
version = "1.0.0"
edition = "2024"

[lib]
crate-type = ["rlib"]

[dependencies]
freedom-log = { workspace = true }
freedom-scheme = { workspace = true }

smol = "2.0.2"
